### ISSUE TITLE
Estudar a análise da espectroscopia

### ISSUE THREAD

**Issue by gabibguedes** [gabibguedes/lunar_discovery#4]
- [x] Estudar como fazer a analise dos minérios 
- [x] Estudar como os dados serão salvos para a analise

**Comment by jkn0t** [comment]
A grosso modo, a análise de minérios feitas através da espectroscopia é feita com um aparelho composto com um laser LBIS e uma câmera RMI. O laser "desintegra" a rocha e a câmera fornece amostra de imagens em alta resolução do espectro do material.

Outra maneira e fazer tal experimento é com feixes de raios-X, que possui menos requisitos de consumo de energia, peso e tamanho. Basicamente, irradiamos as amostras de rochas em pó com partículas alfa na estrutura cristalina e mapeamos, com uma análise de difração, os espectros de raio-X reemitidos, com desvios de ângulos característicos, para determinar a composição dos elementos das amostras.
